/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproject;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form frame3
     */
    public Login() {
        initComponents();
        setTitle("Login and Registration Form");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        P1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pasw1 = new javax.swing.JPasswordField();
        change = new javax.swing.JButton();
        ADMIN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        RPAN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        REGU = new javax.swing.JLabel();
        REGPA = new javax.swing.JLabel();
        PN = new javax.swing.JTextField();
        PU = new javax.swing.JTextField();
        PREG = new javax.swing.JButton();
        PEMAIL = new javax.swing.JLabel();
        DE = new javax.swing.JTextField();
        DP = new javax.swing.JPasswordField();
        PCONTACT = new javax.swing.JLabel();
        DCN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        DPAN = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        DREG = new javax.swing.JLabel();
        DNAME = new javax.swing.JLabel();
        DCONTACT = new javax.swing.JLabel();
        DN = new javax.swing.JTextField();
        DC = new javax.swing.JTextField();
        DREGG = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        DSELECT = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DEMAIL = new javax.swing.JLabel();
        DEM = new javax.swing.JTextField();
        DPASW = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ADMINF = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ADMINUSER = new javax.swing.JTextField();
        ADMINPAS = new javax.swing.JPasswordField();
        ADMINLOGIN = new javax.swing.JButton();
        ADMINBACK = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        DRLOGIN = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DRU = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));
        setResizable(false);

        P1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("USERNAME");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("PASSWORD");

        user1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setText("LOGIN");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("LOGIN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pasw1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 1, true));

        change.setBackground(new java.awt.Color(153, 204, 255));
        change.setText("DOCTOR");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        ADMIN.setBackground(new java.awt.Color(153, 204, 255));
        ADMIN.setText("ADMIN");
        ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setText("PATIENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\user (1)s.png")); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\padlocks.png")); // NOI18N

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton5.setText("FORGET PASSWORD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(P1Layout.createSequentialGroup()
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasw1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(change)
                        .addGap(18, 18, 18)
                        .addComponent(ADMIN)
                        .addGap(15, 15, 15)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(10, 10, 10))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(user1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pasw1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15)))
                .addGap(47, 47, 47)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(34, 34, 34)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(ADMIN)
                    .addComponent(change))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setAutoscrolls(true);
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        RPAN.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("PATIENT REGISTER");

        javax.swing.GroupLayout RPANLayout = new javax.swing.GroupLayout(RPAN);
        RPAN.setLayout(RPANLayout);
        RPANLayout.setHorizontalGroup(
            RPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RPANLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RPANLayout.setVerticalGroup(
            RPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RPANLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("FULL NAME");

        REGU.setText("USERNAME");

        REGPA.setText("CREATE PASSWORD");

        PN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 51)));
        PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNActionPerformed(evt);
            }
        });

        PU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 51)));
        PU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUActionPerformed(evt);
            }
        });

        PREG.setBackground(new java.awt.Color(153, 204, 255));
        PREG.setText("REGISTER");
        PREG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREGActionPerformed(evt);
            }
        });

        PEMAIL.setText("EMAIL");

        DE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 51)));

        DP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));

        PCONTACT.setText("CONTACT NUMBER");

        DCN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 51)));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\technology.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RPAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(PREG)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGU, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCONTACT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DE)
                    .addComponent(DCN)
                    .addComponent(DP)
                    .addComponent(PU, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(PN))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(RPAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGU, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DCN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(PREG)
                .addGap(54, 54, 54))
        );

        jLayeredPane1.add(jPanel1, "card2");

        DPAN.setBackground(new java.awt.Color(204, 204, 204));
        DPAN.setAutoscrolls(true);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(333, 41));

        DREG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DREG.setText("DOCTOR REGISTERATION");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(DREG)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DREG, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        DNAME.setText("DR:NAME");

        DCONTACT.setText("DEGREE");

        DN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        DC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));
        DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCActionPerformed(evt);
            }
        });

        DREGG.setBackground(new java.awt.Color(153, 204, 255));
        DREGG.setText("REGISTER");
        DREGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DREGGActionPerformed(evt);
            }
        });

        BACK.setBackground(new java.awt.Color(153, 204, 255));
        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        DSELECT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Cardiologist", "Anesthesiologist", "Gastroenterologist", "Medical Geneticist", "Clinical Dietician", "Clinical Nutrionist", "Cosmetic Dentist", "Cosmetic Surgeon", "Counselor", "Diabetologist", "Eye Specialist", "Eye Surgeon", "Gynecologist", "Hematologist", "Family Medicine", "Others" }));
        DSELECT.setBorder(null);
        DSELECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSELECTActionPerformed(evt);
            }
        });

        jLabel6.setText("SPECIALIST");

        jLabel8.setText("TIMING");

        DEMAIL.setText("FEES");

        DEM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        DPASW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\person.png")); // NOI18N

        javax.swing.GroupLayout DPANLayout = new javax.swing.GroupLayout(DPAN);
        DPAN.setLayout(DPANLayout);
        DPANLayout.setHorizontalGroup(
            DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addGroup(DPANLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DPANLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DPANLayout.createSequentialGroup()
                        .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DNAME)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPANLayout.createSequentialGroup()
                        .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(DEM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DPASW)
                            .addComponent(DSELECT, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DN)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPANLayout.createSequentialGroup()
                                .addComponent(DREGG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BACK))
                            .addGroup(DPANLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel18)))
                        .addGap(25, 25, 25))))
        );
        DPANLayout.setVerticalGroup(
            DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPANLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DSELECT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DPASW, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DEM, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DCONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(DPANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACK)
                    .addComponent(DREGG))
                .addGap(35, 35, 35))
        );

        jLayeredPane1.add(DPAN, "card3");
        DPAN.getAccessibleContext().setAccessibleName("");

        ADMINF.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("LOGIN AS ADMIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("USERNAME");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("PASSWORD");

        ADMINUSER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        ADMINPAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51)));

        ADMINLOGIN.setBackground(new java.awt.Color(153, 204, 255));
        ADMINLOGIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ADMINLOGIN.setText("LOGIN");
        ADMINLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINLOGINActionPerformed(evt);
            }
        });

        ADMINBACK.setBackground(new java.awt.Color(153, 204, 255));
        ADMINBACK.setText("BACK");
        ADMINBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINBACKActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\user (1)s.png")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\padlocks.png")); // NOI18N

        javax.swing.GroupLayout ADMINFLayout = new javax.swing.GroupLayout(ADMINF);
        ADMINF.setLayout(ADMINFLayout);
        ADMINFLayout.setHorizontalGroup(
            ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ADMINFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ADMINFLayout.createSequentialGroup()
                        .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ADMINFLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ADMINFLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11)))
                        .addGap(22, 22, 22)
                        .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ADMINPAS, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(ADMINUSER)))
                    .addGroup(ADMINFLayout.createSequentialGroup()
                        .addComponent(ADMINBACK)
                        .addGap(18, 18, 18)
                        .addComponent(ADMINLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        ADMINFLayout.setVerticalGroup(
            ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADMINFLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ADMINFLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ADMINUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ADMINFLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ADMINFLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ADMINPAS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(ADMINFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADMINLOGIN)
                    .addComponent(ADMINBACK))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jLayeredPane1.add(ADMINF, "card4");

        DRLOGIN.setBackground(new java.awt.Color(204, 204, 204));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("FORGET PASSWORD");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("ENTER EMAIL");

        DRU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setText("CHECK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fiza\\Documents\\NetBeansProjects\\FinalProject\\src\\main\\java\\com\\mycompany\\finalproject\\forgot-password.png")); // NOI18N

        javax.swing.GroupLayout DRLOGINLayout = new javax.swing.GroupLayout(DRLOGIN);
        DRLOGIN.setLayout(DRLOGINLayout);
        DRLOGINLayout.setHorizontalGroup(
            DRLOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DRLOGINLayout.createSequentialGroup()
                .addGroup(DRLOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DRLOGINLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(DRLOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(DRLOGINLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3))
                            .addComponent(DRU, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DRLOGINLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel14)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        DRLOGINLayout.setVerticalGroup(
            DRLOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DRLOGINLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(DRLOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DRU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(DRLOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 191, Short.MAX_VALUE))
        );

        jLayeredPane1.add(DRLOGIN, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String username = user1.getText();
        String password = new String(pasw1.getPassword());

 try{

            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patient_data", "root", "")) {
                String sql = " SELECT * FROM patient where USERNAME=? and PASSWORD=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, user1.getText());
                pst.setString(2, pasw1.getText());
                ResultSet rs = pst.executeQuery();
                if(username.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "PLEASE ENTER USERNAME");
                }
                else if(password.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "PLEASE ENTER PASSWORD");
                }
                else if(rs.next()){
                    JOptionPane.showMessageDialog(rootPane, "Username and Password Matched!");
                    frameP f2 = new frameP();
                    Login f3 = new Login();
                    String username1 = rs.getString("USERNAME");
                    
                    String name1 = rs.getString("FULL_NAME");
                    String email1 = rs.getString("EMAIL");
                    String contact1 = rs.getString("CONTACT_NUM");
                    
                    f3.setVisible(false);
                    f2.setVisible(true);
                    f2.USER.setText(username1);
                    f2.namee.setText(name1);
                    f2.email.setText(email1);
                    f2.contact.setText(contact1);
                     dispose();
                    
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Username and Password incorrect!");
                    user1.setText("");
                    pasw1.setText("");
                }
            }
        }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        jPanel1.setVisible(false);
        ADMINF.setVisible(false);
        DPAN.setVisible(true);
    }//GEN-LAST:event_changeActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
       DPAN.setVisible(false);
       ADMINF.setVisible(false);
       jPanel1.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    private void PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNActionPerformed

    private void PREGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREGActionPerformed
        String NAME = PN.getText().trim();
        String USERNAME = PU.getText().trim();
        String PASSWORD = new String(DP.getPassword()).trim();
        String EMAIL = DE.getText().trim();
        String CONTACT_NUM = DCN.getText().trim();
        if(NAME.isEmpty() || USERNAME.isEmpty() || PASSWORD.isEmpty() || EMAIL.isEmpty() || CONTACT_NUM.isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "FILL ALL THE FIELDS");
                PN.setText("");
                PU.setText("");
                DP.setText("");
                DE.setText("");
                DCN.setText("");
        }else{
         try{

            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patient_data", "root", "")) {

                PreparedStatement pst = con.prepareStatement("insert into patient(FULL_NAME,USERNAME,PASSWORD,EMAIL,CONTACT_NUM)value(?,?,?,?,?)");
               
                pst.setString(1, NAME);
                pst.setString(2, USERNAME);
                pst.setString(3, PASSWORD);
                pst.setString(4, EMAIL);
                pst.setString(5, CONTACT_NUM);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "DATA SAVED");
                PN.setText("");
                PU.setText("");
                DP.setText("");
                DE.setText("");
                DCN.setText("");
       
                
            }
        }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
    }//GEN-LAST:event_PREGActionPerformed

    private void DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCActionPerformed

    private void DSELECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSELECTActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DSELECTActionPerformed

    private void ADMINLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINLOGINActionPerformed
        
        Admin adm = new Admin();
        String username = ADMINUSER.getText();
        String password = new String(ADMINPAS.getPassword());
        if(username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "PLEASE ENTER PASSWORD OR USERNAME ");
        }
        else if(username.equals("FIZZA") && password.equals("12345")){
            dispose();
            adm.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(rootPane, "INCORRECT USERNAME OR PASSWORD");
        ADMINUSER.setText("");
        ADMINPAS.setText("");
        
        }
    }//GEN-LAST:event_ADMINLOGINActionPerformed

    private void ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINActionPerformed
        DPAN.setVisible(false);
        jPanel1.setVisible(false);
        P1.setVisible(false);
        Login f3 = new Login();
        
        
        Dimension preferred = f3.getPreferredSize();
        f3.setResizable(true);
        f3.setPreferredSize(new Dimension(339, 413));
        f3.pack();
       
        ADMINF.setVisible(true);
        
    }//GEN-LAST:event_ADMINActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DPAN.setVisible(false);
        ADMINF.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ADMINBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINBACKActionPerformed
        DPAN.setVisible(false);
        ADMINF.setVisible(false);
        P1.setVisible(true);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_ADMINBACKActionPerformed

    private void DREGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DREGGActionPerformed
 try{

            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patient_data", "root", "")) {
                String sql;
                String NAME = DN.getText().trim();
                //String USERNAME = DU.getText();
                String PASSWORD = DPASW.getText().trim();
                String EMAIL = DEM.getText().trim();
                String CONTACT_NUM = DC.getText().trim();
                String SELECT = DSELECT.getSelectedItem().toString();
                //sql = " INSERT INTO `patient`(`FULL_NAME`, `USERNAME`, `PASSWORD`, `EMAIL`, `CONTACT_NUM`)VALUES ('"+NAME+"','"+USERNAME+"','"+PASSWORD+"','"+EMAIL+"','"+CONTACT_NUM+"')";
                if(NAME.isEmpty()|| PASSWORD.isEmpty() || EMAIL.isEmpty()||CONTACT_NUM.isEmpty()|| SELECT.equals("SELECT")){
                JOptionPane.showMessageDialog(rootPane, "Please fill all fields");
                }
                
                else{
                PreparedStatement pst = con.prepareStatement("insert into doctors(name,speciality,timing,fees,degree)value(?,?,?,?,?)");
               
                pst.setString(1, NAME);
                pst.setString(2, SELECT);
                pst.setString(3, PASSWORD);
                pst.setString(4, EMAIL);
                pst.setString(5, CONTACT_NUM);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "DOCTOR REGISTEREATION COMPLETED");
                DN.setText("");
                //DU.setText("");
                DPASW.setText("");
                DEM.setText("");
                DC.setText("");
                DSELECT.setSelectedItem("SELECT");
                //ResultSet rs = pst.executeQuery();
                }
        
            }
        }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_DREGGActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DPAN.setVisible(false);
        ADMINF.setVisible(false);
        P1.setVisible(true);
        DRLOGIN.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{

            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/patient_data", "root", "")) {
                String sql = " SELECT * FROM patient where EMAIL=?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, DRU.getText());
                //pst.setString(2, DRP.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(rootPane, "EMAIL FOUND");
                    String password = rs.getString("PASSWORD");
                    JOptionPane.showMessageDialog(rootPane, "YOUR PASSWORD IS: " + password);
                    DRU.setText("");

                    
                    
                }else{
                    JOptionPane.showMessageDialog(rootPane, "EMAIL DOES NOT EXIST!");
                    DRU.setText("");
                    
                }
            }
        }catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DPAN.setVisible(false);
        ADMINF.setVisible(false);
        jPanel1.setVisible(false);
        DRLOGIN.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ADMIN;
    public javax.swing.JButton ADMINBACK;
    public javax.swing.JPanel ADMINF;
    public javax.swing.JButton ADMINLOGIN;
    public javax.swing.JPasswordField ADMINPAS;
    public javax.swing.JTextField ADMINUSER;
    public javax.swing.JButton BACK;
    public javax.swing.JTextField DC;
    public javax.swing.JTextField DCN;
    public javax.swing.JLabel DCONTACT;
    public javax.swing.JTextField DE;
    public javax.swing.JTextField DEM;
    public javax.swing.JLabel DEMAIL;
    public javax.swing.JTextField DN;
    public javax.swing.JLabel DNAME;
    public javax.swing.JPasswordField DP;
    public javax.swing.JPanel DPAN;
    public javax.swing.JTextField DPASW;
    public javax.swing.JLabel DREG;
    public javax.swing.JButton DREGG;
    public javax.swing.JPanel DRLOGIN;
    public javax.swing.JTextField DRU;
    public javax.swing.JComboBox<String> DSELECT;
    public volatile javax.swing.JPanel P1;
    public javax.swing.JLabel PCONTACT;
    public javax.swing.JLabel PEMAIL;
    public javax.swing.JTextField PN;
    public javax.swing.JButton PREG;
    public javax.swing.JTextField PU;
    public javax.swing.JLabel REGPA;
    public javax.swing.JLabel REGU;
    public javax.swing.JPanel RPAN;
    public javax.swing.JButton change;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPasswordField jPasswordField1;
    public volatile javax.swing.JPasswordField pasw1;
    public javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
